# Generated by Django 5.2.2 on 2025-06-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('enlace_inscripcion', models.URLField(blank=True, max_length=500)),
                ('descripcion', models.TextField()),
                ('enlace_cronograma', models.URLField(blank=True, max_length=500)),
                ('enlace_extra', models.URLField(blank=True, max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actividades/')),
            ],
        ),
        migrations.CreateModel(
            name='CicloAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('semestre', models.IntegerField()),
                ('fecha_fin', models.DateField()),
                ('archivado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenGeneralNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='nosotros/')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroPsicopedagogia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('frase', models.TextField()),
                ('foto', models.ImageField(upload_to='psicopedagogia/')),
            ],
        ),
        migrations.CreateModel(
            name='CicloActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo_actividades', to='psicopedagogia.actividad')),
                ('ciclo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo_actividades', to='psicopedagogia.cicloacademico')),
            ],
            options={
                'unique_together': {('ciclo_academico', 'actividad')},
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('enlace_inscripcion', models.URLField(blank=True, max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('ciclo_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='psicopedagogia.cicloacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerias', to='psicopedagogia.cicloactividad')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='galerias/')),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='psicopedagogia.galeria')),
            ],
        ),
    ]
