# Generated by Django 5.2.2 on 2025-06-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicopedagogia', '0001_initial'),
    ]

    operations = [
    ]
