# Generated by Django 5.2.2 on 2025-06-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicopedagogia', '0002_auto_20250618_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='url',
        ),
        migrations.AddField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='galerias/'),
        ),
    ]
