# Generated by Django 5.2.2 on 2025-06-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicopedagogia', '0003_remove_foto_url_foto_imagen'),
        ('psicopedagogia', '0004_add_archive_trigger'),
    ]

    operations = [
    ]
